[tool.poetry]
name = "dbbs-django-logger"
version = "0.1.0"
description = "A Django logging module for CloudWatch and console output"
authors = ["Hryhoriy Bilenko <hryhoriy.bilenko@dbbsoftware.com>"]
readme = "README.md"

[tool.ruff]
extend = "../../common/pyproject.toml"

[tool.poetry.dependencies]
python = "3.11.6"
boto3 = "1.34.0"
django = "5.0.7"
watchtower = "2.0"
common = {path = "../../common"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
