mobile-app:
  - 'typescript/apps/mobile-app/**'
mobile-expo-app:
  - 'typescript/apps/mobile-expo-app/**'
server-api:
  - 'typescript/apps/server-api/**'
serverless-api:
  - 'typescript/apps/serverless-api/**'
serverless-api-cqrs:
  - 'typescript/apps/serverless-api-cqrs/**'
serverless-settings-service:
  - 'typescript/apps/serverless-settings-service/**'
strapi:
  - 'typescript/apps/strapi/**'
strapi-payment-spa:
  - 'typescript/apps/strapi-payment-spa/**'
web-spa:
  - 'typescript/apps/web-spa/**'
web-ssr:
  - 'typescript/apps/web-ssr/**'

# Packages
common:
  - 'typescript/packages/common/**'
cypress:
  - 'packages/cypress/**'
eslint-config:
  - 'typescript/packages/eslint-config/**'
feature-config:
  - 'packages/feature-config/**'
jest-config:
  - 'typescript/packages/jest-config/**'
mobile-components:
  - 'typescript/packages/mobile-components/**'
mobile-features:
  - 'typescript/packages/mobile-features/**'
#mobile-storages:
mobile-jotai-storage:
  - 'typescript/packages/mobile-storages/jotai-storage/**'
mobile-redux-storage:
  - 'typescript/packages/mobile-storages/rtk-storage/**'

mui-components:
  - 'typescript/packages/mui-components/**'
#nestjs-modules:
nestjs-module-auth-jwt:
  - 'typescript/packages/nestjs-modules/auth-jwt/**'
nestjs-module-authz:
  - 'typescript/packages/nestjs-modules/authz/**'
nestjs-module-decorators:
  - 'typescript/packages/nestjs-modules/decorators/**'
nestjs-module-health:
  - 'typescript/packages/nestjs-modules/health/**'
nestjs-module-healthcheck:
  - 'typescript/packages/nestjs-modules/healthcheck/**'
nestjs-module-logger:
  - 'typescript/packages/nestjs-modules/logger/**'
nestjs-module-settings:
  - 'typescript/packages/nestjs-modules/settings/**'
nestjs-module-strapi-roles:
  - 'typescript/packages/nestjs-modules/strapi-roles/**'
nestjs-module-stripe:
  - 'typescript/packages/nestjs-modules/stripe/**'
nestjs-module-stripe-payment:
  - 'typescript/packages/nestjs-modules/stripe-payment/**'

s3-log-transport:
  - 'typescript/packages/s3-log-transport/**'
sendgrid:
  - 'typescript/packages/sendgrid/**'
#strapi-plugins:
strapi-plugin-permissions-manager:
  - 'typescript/packages/strapi-plugins/permissions-manager/**'
strapi-plugin-stripe-payment:
  - 'typescript/packages/strapi-plugins/stripe-payment/**'

tailwind-components:
  - 'typescript/packages/tailwind-components/**'
tsconfig:
  - 'typescript/packages/tsconfig/**'
web-features:
  - 'typescript/packages/web-features/**'
#web-storages:
web-jotai-storage:
  - 'typescript/packages/web-storages/jotai-storage/**'
web-redux-storage:
  - 'typescript/packages/web-storages/rtk-storage/**'
