django-server:
  - 'apps/django-server/**'
  - 'package.json'
  - 'yarn.lock'
mobile-app:
  - 'apps/mobile-app/**'
  - 'package.json'
  - 'yarn.lock'
mobile-expo-app:
  - 'apps/mobile-expo-app/**'
  - 'package.json'
  - 'yarn.lock'
server-api:
  - 'apps/server-api/**'
  - 'package.json'
  - 'yarn.lock'
serverless-api:
  - 'apps/serverless-api/**'
  - 'package.json'
  - 'yarn.lock'
serverless-api-cqrs:
  - 'apps/serverless-api-cqrs/**'
  - 'package.json'
  - 'yarn.lock'
serverless-settings-service:
  - 'apps/serverless-settings-service/**'
  - 'package.json'
  - 'yarn.lock'
strapi:
  - 'apps/strapi/**'
  - 'package.json'
  - 'yarn.lock'
strapi-payment-spa:
  - 'apps/strapi-payment-spa/**'
  - 'package.json'
  - 'yarn.lock'
web-spa:
  - 'apps/web-spa/**'
  - 'package.json'
  - 'yarn.lock'
web-ssr:
  - 'apps/web-ssr/**'
  - 'package.json'
  - 'yarn.lock'

# Packages
common:
  - 'packages/common/**'
  - 'package.json'
  - 'yarn.lock'
cypress:
  - 'packages/cypress/**'
  - 'package.json'
  - 'yarn.lock'
eslint-config:
  - 'packages/eslint-config/**'
  - 'package.json'
  - 'yarn.lock'
feature-config:
  - 'packages/feature-config/**'
  - 'package.json'
  - 'yarn.lock'
jest-config:
  - 'packages/jest-config/**'
  - 'package.json'
  - 'yarn.lock'
mobile-components:
  - 'packages/mobile-components/**'
  - 'package.json'
  - 'yarn.lock'
mobile-features:
  - 'packages/mobile-features/**'
  - 'package.json'
  - 'yarn.lock'
#mobile-storages:
mobile-jotai-storage:
  - 'packages/mobile-storages/jotai-storage/**'
  - 'package.json'
  - 'yarn.lock'
mobile-redux-storage:
  - 'packages/mobile-storages/rtk-storage/**'
  - 'package.json'
  - 'yarn.lock'

mui-components:
  - 'packages/mui-components/**'
  - 'package.json'
  - 'yarn.lock'
#nestjs-modules:
nestjs-module-auth-jwt:
  - 'packages/nestjs-modules/auth-jwt/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-authz:
  - 'packages/nestjs-modules/authz/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-decorators:
  - 'packages/nestjs-modules/decorators/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-health:
  - 'packages/nestjs-modules/health/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-healthcheck:
  - 'packages/nestjs-modules/healthcheck/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-logger:
  - 'packages/nestjs-modules/logger/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-settings:
  - 'packages/nestjs-modules/settings/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-strapi-roles:
  - 'packages/nestjs-modules/strapi-roles/**'
  - 'package.json'
  - 'yarn.lock'
nestjs-module-stripe:
  - 'packages/nestjs-modules/stripe/**'
  - 'package.json'
  - 'yarn.lock'

s3-log-transport:
  - 'packages/s3-log-transport/**'
  - 'package.json'
  - 'yarn.lock'
sendgrid:
  - 'packages/sendgrid/**'
  - 'package.json'
  - 'yarn.lock'
#strapi-plugins:
strapi-plugin-permissions-manager:
  - 'packages/strapi-plugins/permissions-manager/**'
  - 'package.json'
  - 'yarn.lock'
strapi-plugin-stripe-payment:
  - 'packages/strapi-plugins/stripe-payment/**'
  - 'package.json'
  - 'yarn.lock'

tailwind-components:
  - 'packages/tailwind-components/**'
  - 'package.json'
  - 'yarn.lock'
tsconfig:
  - 'packages/tsconfig/**'
  - 'package.json'
  - 'yarn.lock'
web-features:
  - 'packages/web-features/**'
  - 'package.json'
  - 'yarn.lock'
#web-storages:
web-jotai-storage:
  - 'packages/web-storages/jotai-storage/**'
  - 'package.json'
  - 'yarn.lock'
web-redux-storage:
  - 'packages/web-storages/rtk-storage/**'
  - 'package.json'
  - 'yarn.lock'
