# https://docs.sonarcloud.io/advanced-setup/analysis-scope/
sonar.projectKey=dbb-software_dbbs-solutions_python
sonar.organization=dbb-software
sonar.host.url=https://sonarcloud.io
sonar.projectName=DBB Software Platform Base Python

sonar.sources=python

sonar.python.version=3.11.6

sonar.python.coverage.reportPaths= \
    python/apps/**/coverage.xml, \
    python/packages/**/coverage.xml

sonar.cpd.exclusions= **/tests/*
sonar.coverage.exclusions= \
    **/tests.py, \
    **/tests/*, \
    python/django-server/core/**, \
    python/django-server/*/migrations
