const PREFIX = 'geo-config'

export const GEO_CONFIG_FORM_TEST_IDS = {
  FORM: `${PREFIX}-form`,
  NAME: `${PREFIX}-name`,
  GEO_TYPE: `${PREFIX}-geo-type`,
  TIMEZONE: `${PREFIX}-timezone`,
  SCHEDULE_URL: `${PREFIX}-schedule-url`,
  CAPTURE_STREAM_FLAG: `${PREFIX}-capture-stream-flag`,
  CAPTURE_SCHEDULE_FLAG: `${PREFIX}-capture-schedule-flag`,
  STREAM_TYPE: `${PREFIX}-stream-type`,
  JURISDICTION: `${PREFIX}-jurisdiction`,
  PARENT: `${PREFIX}-parent`,
  SORT_KEY: `${PREFIX}-sort-key`,
  CHANNEL_URL: `${PREFIX}-channel-url`,
  STATUS_SCHEDULE: `${PREFIX}-status-schedule`,
  SCHEDULE_LAST_REFRESH: `${PREFIX}-schedule-last-refresh`,
  MIRROR_GEO: `${PREFIX}-mirror-geo`,
  SCHEDULE_FORMAT: `${PREFIX}-schedule-format`,
  SUBMIT_BUTTON: `${PREFIX}-submit-button`,
  DETECT_START_METHOD: `${PREFIX}-detect-start-method`,
  DETECT_END_METHOD: `${PREFIX}-detect-end-method`,
  STATUS_STREAM: `${PREFIX}-status-stream`,
  FLAG_AGENDA: `${PREFIX}-flag-agenda`,
  FLAG_OPT_IN: `${PREFIX}-flag-opt-in`,
  FLAG_LIVE: `${PREFIX}-flag-live`,
  DEBUG: `${PREFIX}-debug`,
  DEMO: `${PREFIX}-demo`,
  SCHEDULE_REFRESH_FREQUENCY: `${PREFIX}-schedule-refresh-frequency`,
  DETECT_END_OCR: `${PREFIX}-detect-end-ocr`,
  SINGLE_PLAYER_URL: `${PREFIX}-single-player-url`
}
