export const envVars = {
  LOCAL_STAGE: 'local',
  REGION: 'REGION',
  STAGE: 'STAGE',
  SQS_QUEUE_URL: 'SQS_QUEUE_URL',
  S3_DOCUMENTS_BUCKET: 'S3_DOCUMENTS_BUCKET',
  S3_DOCUMENTS_BUCKET_URL: 'S3_DOCUMENTS_BUCKET_URL'
}
