name: 'Build and Tests'
description: 'Execute common steps necessary for checking applications build and tests'

inputs:
  ref:
    description: Ref for checkout. Use the github.ref
    required: true
  aws_credentials:
    description: Credentials for the AWS. Should be the github secret AWS_CREDENTIALS
    required: true
  aws_config:
    description: Config for the AWS. Should be the github secret AWS_CONFIG
    required: true
  sonar_token:
    description: Token for SonarCloud.
    required: false
  github_token:
    description: Github token for SonarCloud.
    required: false

runs:
  using: "composite"
  steps:
    - name: Use Setup Yarn action
      uses: ./.github/actions/setup-yarn

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Setup Python
      uses: ./.github/actions/setup-python

    - name: Set up NodeJs
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        cache: 'yarn'

    - name: Cache node_modules
      if: ${{ github.event.pull_request.draft == true }}
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install project dependencies
      run: |
        node -v
        npm -v
        yarn --immutable
      shell: bash

    - name: Verify dependencies are unchanged
      run: |
        (git diff --exit-code yarn.lock && git diff --exit-code package.json) || echo \
          "::error::There was a dependency updated during installation. Install locally and commit changes"
      shell: bash

    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@master

    - name: Configure AWS Credentials
      run: |
        mkdir -p ~/.aws/
        echo "${{ inputs.aws_credentials }}" > ~/.aws/credentials
        echo "${{ inputs.aws_config }}" > ~/.aws/config
      shell: bash

    - name: Run tests
      run: |
        yarn download:env
        yarn test
      env:
        STAGE: development
        AWS_PROFILE: dbbs-development
        SECRET_PREFIX: dbbs-pre-built-solutions
      shell: bash

    - name: Override Coverage Source Path for Sonar
      run: sed -i "s|<source>.*</source>|<source>/github/workspace/apps/django-server</source>|g" apps/django-server/coverage.xml
      shell: bash

    - name: Sonarcloud Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_HOST_URL: "https://sonarcloud.io"
