"""fix
Revision ID: f26d942516d5
Revises: aa0e6c962a4e
Create Date: 2025-02-26 12:49:02.754252
"""



# revision identifiers, used by Alembic.
revision = 'f26d942516d5'
down_revision = 'aa0e6c962a4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
