"""setup
Revision ID: aa0e6c962a4e
Revises: 
Create Date: 2025-02-26 12:35:09.109214
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'aa0e6c962a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('geo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capture_schedule_flag', sa.Boolean(), nullable=True),
    sa.Column('capture_stream_flag', sa.Boolean(), nullable=True),
    sa.Column('meeting_type_id', sa.Integer(), nullable=True),
    sa.Column('schedule_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=200), nullable=True),
    sa.Column('schedule_format', sa.String(length=200), nullable=True),
    sa.Column('jurisdiction', sa.Boolean(), nullable=True),
    sa.Column('channel_url', sa.String(length=500), nullable=True),
    sa.Column('status_schedule', sa.String(length=200), nullable=True),
    sa.Column('status_stream', sa.String(length=50), nullable=True),
    sa.Column('flag_only_agenda', sa.Boolean(), nullable=True),
    sa.Column('flag_opt_in_only', sa.Boolean(), nullable=True),
    sa.Column('single_player_url', sa.String(length=500), nullable=True),
    sa.Column('flag_live', sa.Boolean(), nullable=True),
    sa.Column('detect_end_method', sa.String(length=100), nullable=True),
    sa.Column('detect_start_method', sa.String(length=100), nullable=True),
    sa.Column('detect_end_ocr_string', sa.String(length=200), nullable=True),
    sa.Column('debug', sa.Boolean(), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=True),
    sa.Column('schedule_refresh_frequency', sa.Integer(), nullable=True),
    sa.Column('geo_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['geo_parent_id'], ['geo.id'], ),
    sa.ForeignKeyConstraint(['meeting_type_id'], ['meeting_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo')
    op.drop_table('meeting_type')
    # ### end Alembic commands ###
