import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { type ReactNode } from 'react'
import './global.css'
import AppLayout from '../component/ui/main-layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {
          <SessionProvider>
            <AppLayout>{children}</AppLayout>
          </SessionProvider>
        }
      </body>
    </html>
  )
}
