name: 'Setup Python env for test'
description: |
  Install Python and poetry for tests.

runs:
  using: 'composite'
  steps:
    - name: Determine versions
      shell: bash -leo pipefail {0}
      id: get_versions
      run: |
        python="$(grep -v '#' .tool-versions | grep python | awk '{print $2}')"
        echo "python=${python}" >> $GITHUB_OUTPUT

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.get_versions.outputs.python }}

    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
      shell: bash

    - name: Modify poetry config
      run: |
        poetry config virtualenvs.in-project true
        poetry config installer.parallel false
      shell: bash
