name: flutter_mobile
description: A new Flutter application

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # Firebase packages with custom package path
  firebase:
    path: ../../packages/firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_remote_config: ^5.4.2

  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env.development
    - .env.production
    - assets/images/
    - assets/firebase/
