name: Auto run of E2E tests for a specific mobile application.

run-name: Test ${{ github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-dev:
    if: ${{ github.ref || 'refs/heads/main' }}
    runs-on: self-hosted
    timeout-minutes: 60
    environment: ${{ format('{0}_{1}', 'mobile-app', 'development') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build, and e2e
        uses: ./.github/actions/build-and-e2e-ios
        with:
          ref: ${{ github.ref }}
          ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
          workspace: mobile-app
          restore_key: './typescript/apps/mobile-app/package.json'
          pods_restore_key: './typescript/apps/mobile-app/ios/Podfile.lock'
