name: Run tests

run-name: Test ${{ github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'apps/**'
      - 'package.json'
      - 'packages/**'
      - 'yarn.lock'

jobs:
  prepare-cache:
    uses: ./.github/workflows/nodejs-cache.yaml
    if: github.event.pull_request.draft == false

  changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/change_path_filter.yaml

  test-changed-apps:
    needs:
      - prepare-cache
      - changes
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        app: ${{fromJson(needs.changes.outputs.apps)}}
    uses: ./.github/workflows/nodejs-test.yaml
    with:
      app_name: ${{ matrix.app }}
