name: Run tests based on changes

run-name: Test ${{ github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'python/**'
      - 'typescript/**'
      - 'packages/**'

jobs:
  prepare-cache:
    uses: ./.github/workflows/nodejs-cache.yaml
    if: github.event.pull_request.draft == false

  changes:
    name: Changes for ${{ matrix.app_type }}
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        app_type: [python, nodejs]
    outputs:
      python_apps: ${{ matrix.app_type == 'python' && steps.filter.outputs.changes || '[]' }}
      nodejs_apps: ${{ matrix.app_type == 'nodejs' && steps.filter.outputs.changes || '[]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: ${{ matrix.app_type == 'python' && '.github/change_path_filter_python.yaml' || matrix.app_type == 'nodejs' && '.github/change_path_filter_nodejs.yaml' }}

  test-nodejs-apps:
    needs:
      - prepare-cache
      - changes
    if: needs.changes.outputs.nodejs_apps != '[]' && github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        app: ${{ fromJson(needs.changes.outputs.nodejs_apps) }}
    uses: ./.github/workflows/nodejs-test.yaml
    with:
      app_name: ${{ matrix.app }}
      runs_on: '["ubuntu-24.04"]'
      timeout: 45

  test-python-apps:
    needs:
      - prepare-cache
      - changes
    if: needs.changes.outputs.python_apps != '[]' && github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        app: ${{ fromJson(needs.changes.outputs.python_apps) }}
    uses: ./.github/workflows/python-test.yaml
    with:
      app_name: ${{ matrix.app }}
      runs_on: '["ubuntu-24.04"]'
      timeout: 45
