name: Manual run of E2E tests for a specific mobile application.

run-name: Test ${{ github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform of mobile application
        required: true
        type: choice
        default: ios
        options:
          - ios
          - android
      workspace:
        description: A folder of mobile application
        required: true
        type: choice
        default: mobile-app
        options:
          - mobile-app
          - mobile-expo-app
      # Android-specific inputs
      device_api:
        description: Version of API for android, which will be used for creating android emulator.
        required: false
        type: choice
        default: 34
        options:
          - 34
          - 35
      device_profile:
        description: Profile of device, which will be used for creating android emulator.
        required: false
        type: choice
        default: pixel
        options:
          - pixel
          # For up-to-date device lists, run the command: avdmanager list device 
      device_target:
        description: Target of the system image, which will be used for creating android emulator.
        required: false
        type: choice
        default: default
        options:
          - default
          - google_apis
          - playstore
          - android-wear
          - android-wear-cn
jobs:
  test-dev:
    runs-on: ${{ inputs.platform == 'ios' && 'self-hosted' || 'ubuntu-24.04' }}
    timeout-minutes: 60
    environment: ${{ format('{0}_{1}', inputs.workspace, 'development') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build, and e2e for ios platform
        if: ${{ inputs.platform == 'ios' }}
        uses: ./.github/actions/build-and-e2e-ios
        with:
          ref: ${{ github.ref }}
          ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
          workspace: ${{ inputs.workspace }}
          restore_key: './typescript/apps/${{ inputs.workspace }}/package.json'
          pods_restore_key: './typescript/apps/${{ inputs.workspace }}/ios/Podfile.lock'

      - name: Run build, and e2e for android platform
        if: ${{ inputs.platform == 'android' }}
        uses: ./.github/actions/build-and-e2e-android
        with:
          ref: ${{ github.ref }}
          ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
          SIGNING_CREDENTIALS: ${{ secrets.SIGNING_CREDENTIALS }}
          workspace: ${{ inputs.workspace }}
          device_api: ${{ inputs.device_api }}
          device_profile: ${{ inputs.device_profile }}
          device_target: ${{ inputs.device_target }}
          restore_key: './typescript/apps/${{ inputs.workspace }}/package.json'
