name: nodejs-cache

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        description: 'Platform to execute on. Default ["ubuntu-22.04"]'
        type: string
        default: '["ubuntu-22.04"]'

      node_version_file:
        required: false
        description: 'File with nodejs version. Default ".tool-versions"'
        type: string
        default: '.tool-versions'

      timeout:
        required: false
        description: "Timeout in minutes for the job execution. Defaults 15."
        type: number
        default: 15

jobs:
  prepare-cache:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure node environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}

      - name: Use Setup Yarn action
        uses: ./.github/actions/setup-yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "dir=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - name: Restore cache
        uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-${{ hashFiles('./yarn.lock') }}
          lookup-only: true
          restore-keys: |
            yarn-${{ github.ref_name }}-

      - name: Build dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          yarn install --immutable

      - name: Cache Yarn dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            yarn-${{ github.ref_name }}-
