name: Test Python

run-name: Test Python ${{ github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - python/**
      - .github/workflows/test_python.yml
      - .github/actions/setup-python.yml
      - .github/actions/setup-yarn.yml
      - .github/actions/setup-node.yml
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Fetch main branch
        if: github.ref != 'refs/heads/main'
        run: |
          git fetch origin main:main

      - name: Cache turbo setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Use Setup Yarn action
        uses: ./.github/actions/setup-yarn

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'   

      - name: Setup Python
        uses: ./.github/actions/setup-python
      
      - name: Build dependencies
        run: |
          yarn install --immutable

      - name: List and extract affected projects
        run: |
          npx turbo ls --affected --output=json > affected.json

          export AFFECTED_PATHS=$(jq -r '.packages.items 
            | map(select(.path | startswith("python/")) | .path = "./" + .path) 
            | map(.path) 
            | join(" ")' affected.json)

          if [ -z "$AFFECTED_PATHS" ] && [ "$GITHUB_EVENT_NAME" != "pull_request" ]; then
            AFFECTED_PATHS="./python/**/*"
          fi

          FILTER_ARGS=$(for path in $AFFECTED_PATHS; do echo "--filter=$path"; done | xargs)
          
          echo "FILTER_ARGS=$FILTER_ARGS" >> $GITHUB_ENV
          echo "AFFECTED_PATHS=$AFFECTED_PATHS" >> $GITHUB_ENV
          
          echo $GITHUB_EVENT_NAME
          echo $AFFECTED_PATHS
        shell: bash

      - name: Install Python deps
        if: ${{ env.AFFECTED_PATHS != '' }}
        run: |
          npx turbo run install:deps

      - name: Typecheck
        if: ${{ env.AFFECTED_PATHS != '' }}
        run: |
          npx turbo check-types ${{ env.FILTER_ARGS }}

      - name: Test
        if: ${{ env.AFFECTED_PATHS != '' }}
        run: |
          npx turbo run test ${{ env.FILTER_ARGS }}

      - name: Alert on main fail
        uses: slackapi/slack-github-action@v2.0.0
        if: failure() && github.ref == 'refs/heads/main'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          payload: |
            channel: ${{ vars.SLACK_ALERTS_CHANNEL_ID }}
            text: ":this-is-fine-fire: *GitHub Action Job auto-run-test-jobs.yml Failed*\n
            *Job*: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
            *Author*: https://github.com/${{ github.actor }}"